name: service_availability_5m

metric:
  name: service.availability.5m
  type: COUNT
  tags:
    - key: env
      value: prod

schedule:
  interval: 5m
  strategy: stateful

source:
  type: prometheus
  config:
    uri: 'http://{{ getEnvOrDefault "SC_PROM_HOST" "localhost" }}:9090/api/v1/query'
    query: 'sum by (result_status_code) (increase(collector_invoke_count_total[5m]))'
    time_duration:
      start_of: 5m
    sql: |
      SELECT
        'signals-collector' as service,
        CASE
          WHEN metric->>'result_status_code' = 'OK'
          THEN false
          ELSE true
        END as error,
        round(value::DOUBLE, 0) as value
      FROM
        prom_metrics

sinks:
  console:
    type: console

  audit:
    type: file
    config:
      path: /tmp/log/signals.audit.log
