name: service_availability_24h

collector:
  type: metric
  invocation_strategy: historic_tumbling_window

state_store:
  type: memory

metric:
  name: service.availability.24h
  type: COUNT
  tags:
    - key: env
      value: prod

schedule:
  interval: 4h

source:
  type: metric.prometheus
  config:
    uri: 'http://{{ getEnvOrDefault "SC_PROM_HOST" "localhost" }}:9090/api/v1/query'
    query: 'sum(round(increase(collector_invoke_count_total[24h]))) by (result_status_code)'
    time:
      window: 24h
    sql: |
      SELECT
        'latte' as service,
        CASE
          WHEN metric->>'result_status_code' = 'OK'
          THEN false
          ELSE true
        END as error,
        round(value::DOUBLE, 0) as value
      FROM
        prom_metrics

sinks:
  audit:
    type: file
    config:
      path: /tmp/log/latte.audit.log
