
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  vector:
    image: timberio/vector:0.34.1-debian
    ports:
      - "8686:8686"
      - "9999:9999"
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro